name: XCS234_A3_CUDA
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8.10
  - notebook=6.5.4
  - tk=8.6.12
  - ffmpeg=4.2.2
  - moviepy=1.0.3
  - scipy=1.10.1
  - tensorboard=2.10.0
  - pyyaml=6.0
  - pip=23.0.1
  - pip:
    - matplotlib==3.7.1
    - imageio==2.28.0
    - numpy==1.24.3
    - pygame==2.3.0
    - dm-control==1.0.12
    - gym==0.26.2
    - mujoco==2.3.5
    - "--find-links https://download.pytorch.org/whl/torch_stable.html"
    - torch==2.0.0+cu117
